export const ADD_CONTACT = "ADD_CONTACT";
export const RECIEVE_CONTACTS = "RECIEVE_CONTACTS";
export const RECIEVE_SINGLE_CONTACT = "RECIEVE_SINGLE_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const EDIT_CONTACT = "DELETE_CONTACT";
export const SET_QUERY = "SET_QUERY";
